language: php
dist: trusty
php:
- 7.2
- 7.3
- 7.4
matrix:
  include:
    - php: 7.2
      script:
      - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
      after_script:
      - php ./vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
before_script:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-dist
script:
- phpunit
